version: "3.9"
   
services:
    db:
        image: public.ecr.aws/ubuntu/postgres:latest
        container_name: local_pgdb
        restart: always
        volumes:
            - ./data/db:/var/lib/postgresql/data
        environment:
            - POSTGRES_NAME=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres

    pgadmin:
        image: public.ecr.aws/u8t5t6k6/dpage/pgadmin4:5
        container_name: local_pgadmin4
        restart: always
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@example.com
            PGADMIN_DEFAULT_PASSWORD: testpassword
            PGADMIN_LISTEN_PORT: 8080
        ports:
            - "8080:8080"
        volumes:
            - pgadmin-data:/var/lib/pgadmin
        links:
            - "db:pgsql-server"

    web:
        build: .
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/code
        ports:
            - "8000:8000"
        environment:
            - POSTGRES_NAME=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        depends_on:
            - db

volumes:
    local_pgdata:
    pgadmin-data: