# Generated by Django 4.0.1 on 2022-01-30 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Map',
            new_name='Point',
        ),
    ]
