# Generated by Django 4.0.1 on 2022-01-31 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_rename_map_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='computer_time',
            field=models.DateTimeField(blank=True, max_length=255, null=True),
        ),
    ]
