# Generated by Django 4.0.1 on 2022-01-31 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_alter_point_computer_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='latest_gps_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='point',
            name='ch4_recordtime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='point',
            name='gps_time_ori',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='point',
            name='gps_time_pos',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='point',
            name='rmys_record_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
